### ISSUE TITLE
Standalone bundled JS dependency 

### ISSUE THREAD

**Issue by maxkarelov** [samsam2310/zbar.wasm#7]
How the package can be bundled to single JS file dependency that can be used in html? I am not strong enough in npm package manager

Thank you in advance!

**Comment by samsam2310** [comment]
Hi,

You need some tools to compile them into bundled Javascript files. You can search some keywords about setup a web project for NPM. Basically, you will need something like "webpack" which helps you to create a single js bundel.

You can also use something like cra ("Create React APP"), which can help you setup all the webpack config and some files for web project.

Because this is not diractly related to this project, I will close this issue.
